### ISSUE TITLE
githubの勉強サイトについて

### ISSUE THREAD

**Issue by a-yuto** [hu-hicoder/web-reading#1]
https://learngitbranching.js.org/
内定先で教えてもらったサイトで、非常にわかりやすかったので共有しておきます。
githubの勉強方法としてこのサイトをするのはどうでしょうか？

**Comment by uta8a** [comment]
ありがとうございます。Gitの使い方を手を動かしながら学べるのはとてもよいですね！今回のweb-readingでは採用する時間がなさそうなのですが、Gitの勉強会を行うときには使ってみたいと思います！

**Comment by uta8a** [comment]
078713c60f9173e9f653133f304d45a79a2f549c で頂いた情報を追加しました。このissueはcloseします。
